version: "2"
services:
  wordpress:
    image: wordpress:latest
    container_name: "mofuplay"
    volumes:
      - "$PWD:/var/www/html"
      - "$PWD/.docker/backup:/tmp/backup"
      - "$PWD/.docker/log:/tmp/log"
    ports:
      - "8888:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    # networks:
    #   - mofuplay-nw
    env_file: .env

  db:
    image: mysql:5.7
    container_name: "mofuplay-db"
    volumes:
      - "db-data:/var/lib/mysql"
    # networks:
    #   - mofuplay-nw
    env_file: .env

volumes:
  db-data:

# networks:
#   mofuplay-nw
